Use latest pyparsing 2.0.x to avoid setuptools entanglement
With 2.0.1, and setuptools 34.0.2, errors happen like:

File "/edx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

(cherry picked from commit 73519b3547359a0b791e39d4665f51ac66449a17)